/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.DiagnosisController;
import Model.DBConnection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author DELL PC
 */
public class Diagnosis extends javax.swing.JFrame {
public int flag = 0;
    /**
     * Creates new form Diagnosis
     */
    public Diagnosis() {
        initComponents();
        DMessageLbl.setVisible(false);
        DWardTypeCb.setVisible(false);
        DWardTypeLbl.setVisible(false);
    }

    Connection conn;
    Statement stmt;
    ResultSet Rs = null;
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        PHistory = new javax.swing.JLabel();
        DInfor = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        DPIdTb = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        DSearchBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        DPatientInforTbl = new javax.swing.JTable();
        DMessageLbl = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        DSymptomTb = new javax.swing.JTextField();
        DDiagnosisTb = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        DMedicinesTb = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        DWRequiredChb = new javax.swing.JCheckBox();
        DWardTypeLbl = new javax.swing.JLabel();
        DWardTypeCb = new javax.swing.JComboBox<>();
        DSaveBtn = new javax.swing.JButton();
        DResetBtn = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1342, 719));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel2.setBackground(new java.awt.Color(153, 153, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Hospital management Software");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(482, 482, 482)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 497, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1351, -1));

        PHistory.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        PHistory.setForeground(new java.awt.Color(102, 102, 255));
        PHistory.setText("Patient History");
        PHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PHistoryMouseClicked(evt);
            }
        });
        getContentPane().add(PHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, -1, -1));

        DInfor.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        DInfor.setForeground(new java.awt.Color(102, 102, 255));
        DInfor.setText("Diagnosis Information");
        getContentPane().add(DInfor, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 90, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/book2.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/stethoscope.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 80, -1, -1));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setPreferredSize(new java.awt.Dimension(50, 2));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 159, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 120, 159, -1));

        DPIdTb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(DPIdTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 158, 144, 32));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Parient ID");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 161, -1, -1));

        DSearchBtn.setBackground(new java.awt.Color(255, 255, 255));
        DSearchBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        DSearchBtn.setForeground(new java.awt.Color(51, 51, 255));
        DSearchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search.png"))); // NOI18N
        DSearchBtn.setText("Search");
        DSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DSearchBtnActionPerformed(evt);
            }
        });
        getContentPane().add(DSearchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(879, 157, 120, -1));

        DPatientInforTbl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        DPatientInforTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Parient ID", "Name", "Phone", "Address", "Gender", "Age", "Blood Group", "Any Major Disease"
            }
        ));
        DPatientInforTbl.setRowHeight(27);
        jScrollPane1.setViewportView(DPatientInforTbl);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 247, 1056, 64));

        DMessageLbl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        DMessageLbl.setForeground(new java.awt.Color(204, 102, 0));
        DMessageLbl.setText("Patient ID Does Not Exist");
        getContentPane().add(DMessageLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 200, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("Symptom's");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 397, -1, -1));

        DSymptomTb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(DSymptomTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 394, 218, 32));

        DDiagnosisTb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(DDiagnosisTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 457, 218, 32));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("Diagnosis");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 460, -1, -1));

        DMedicinesTb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(DMedicinesTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 521, 218, 32));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 255));
        jLabel10.setText("Medicines");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 524, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 255));
        jLabel11.setText("Ward Required");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 397, -1, -1));

        DWRequiredChb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        DWRequiredChb.setForeground(new java.awt.Color(153, 153, 255));
        DWRequiredChb.setText("Yes");
        DWRequiredChb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DWRequiredChbActionPerformed(evt);
            }
        });
        getContentPane().add(DWRequiredChb, new org.netbeans.lib.awtextra.AbsoluteConstraints(922, 397, -1, -1));

        DWardTypeLbl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        DWardTypeLbl.setForeground(new java.awt.Color(0, 0, 255));
        DWardTypeLbl.setText("Type of Ward");
        getContentPane().add(DWardTypeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 460, -1, -1));

        DWardTypeCb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        DWardTypeCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General", "Single", "Duo" }));
        getContentPane().add(DWardTypeCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(922, 456, 167, 32));

        DSaveBtn.setBackground(new java.awt.Color(255, 255, 255));
        DSaveBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        DSaveBtn.setForeground(new java.awt.Color(51, 51, 255));
        DSaveBtn.setText("Save");
        DSaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DSaveBtnActionPerformed(evt);
            }
        });
        getContentPane().add(DSaveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 603, 104, -1));

        DResetBtn.setBackground(new java.awt.Color(255, 255, 255));
        DResetBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        DResetBtn.setForeground(new java.awt.Color(51, 51, 255));
        DResetBtn.setText("Reset");
        DResetBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DResetBtnMouseClicked(evt);
            }
        });
        getContentPane().add(DResetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(728, 603, 104, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Windows-Turn-Off-icon.png"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 660, -1, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton1.setText("Hospital Information");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 70, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back5.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        int a = JOptionPane.showConfirmDialog(null, "Do you want to close the application","Select",JOptionPane.YES_NO_OPTION);
        
        if(a == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        new HospitalInformation().setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void PHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PHistoryMouseClicked
        new PatientHistoryA().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PHistoryMouseClicked

    private void DSaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DSaveBtnActionPerformed
       if(flag==1)//then patient ID is correct.
       {
           stmt = DBConnection.getStatementConnection();
           Integer PatientID = Integer.valueOf(DPIdTb.getText());
           String Symptom = DSymptomTb.getText();
           String Diagnosis = DDiagnosisTb.getText();
           String Medicines = DMedicinesTb.getText();
           String WardReq;
           String TypeWard;
           
           if(DWRequiredChb.isSelected()){
               WardReq = "YES";
               TypeWard = (String)DWardTypeCb.getSelectedItem();
           }
           else{
               WardReq = "NO";
               TypeWard = "";
           }
           DiagnosisController.diagnosisSave(PatientID, Symptom, Diagnosis, Medicines, WardReq, TypeWard);
           setVisible(false);
           new Diagnosis().setVisible(true);
      }
       else{
           JOptionPane.showMessageDialog(null, "PatientID field is Empty");
       }
    }//GEN-LAST:event_DSaveBtnActionPerformed

    private void DWRequiredChbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DWRequiredChbActionPerformed
        if(DWRequiredChb.isSelected()){
            DWardTypeLbl.setVisible(true);
            DWardTypeCb.setVisible(true);
        }
        else{
            DWardTypeLbl.setVisible(false);
            DWardTypeCb.setVisible(false);
        }
    }//GEN-LAST:event_DWRequiredChbActionPerformed

    private void DSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DSearchBtnActionPerformed
        
        String PatientID = DPIdTb.getText();
        try {
            stmt = DBConnection.getStatementConnection();
            Rs = stmt.executeQuery("select * from parienttbl where Patient_ID='"+PatientID+"'");
            DPatientInforTbl.setModel(DbUtils.resultSetToTableModel(Rs));
            if(!Rs.first()){
                DMessageLbl.setVisible(true);
            }
            else{
                DMessageLbl.setVisible(false);
                DPIdTb.setEditable(false);
                flag = 1;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Connction Error");
        }
    }//GEN-LAST:event_DSearchBtnActionPerformed

    private void DResetBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DResetBtnMouseClicked
        setVisible(false);
        new Diagnosis().setVisible(true);
    }//GEN-LAST:event_DResetBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Diagnosis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Diagnosis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Diagnosis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Diagnosis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Diagnosis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DDiagnosisTb;
    private javax.swing.JLabel DInfor;
    private javax.swing.JTextField DMedicinesTb;
    private javax.swing.JLabel DMessageLbl;
    private javax.swing.JTextField DPIdTb;
    private javax.swing.JTable DPatientInforTbl;
    private javax.swing.JButton DResetBtn;
    private javax.swing.JButton DSaveBtn;
    private javax.swing.JButton DSearchBtn;
    private javax.swing.JTextField DSymptomTb;
    private javax.swing.JCheckBox DWRequiredChb;
    private javax.swing.JComboBox<String> DWardTypeCb;
    private javax.swing.JLabel DWardTypeLbl;
    private javax.swing.JLabel PHistory;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
