/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.DoctorController;
import Model.DBConnection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author DELL PC
 */
public class DoctorA extends javax.swing.JFrame {

    /**
     * Creates new form DoctorA
     */
    public DoctorA() {
        initComponents();
        DisplayDoctors();
    }

    
    private void Reset(){
        DAIdTb.setText("");
        DANameTb.setText("");
        DAPhoneTb.setText("");
        DAAddressTb.setText("");
        DATypeCb.setSelectedIndex(0);
        DAPasswordTb.setText("");
    }
    
    Connection conn;
    Statement stmt;
    ResultSet Rs = null;
    
    private void DisplayDoctors(){
        try
        {
            stmt = DBConnection.getStatementConnection();//create statment-> Statement statement = connection.createStatement();
            Rs = stmt.executeQuery("select * from hospital_information.doctortbl");//executing a query via a Statement
            DoctorTbl.setModel(DbUtils.resultSetToTableModel(Rs));
            DBConnection.closeCon();
        }
        catch(Exception e)
        {
           e.printStackTrace(); //This is also can be used-> JOptionPane.showMessageDialog(null, "there is an error in try part of DispalyDoctors method");
        }
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PatientLbl = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        DoctorLbl = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        DAIdTb = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        DANameTb = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        DAPhoneTb = new javax.swing.JTextField();
        DAAddressTb = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Type = new javax.swing.JLabel();
        DATypeCb = new javax.swing.JComboBox<>();
        DAPasswordTb = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        DASaveBtn = new javax.swing.JButton();
        DAResetBtn = new javax.swing.JButton();
        DADeleteBtn = new javax.swing.JButton();
        DAEditBtn = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        DAPrintBtn = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DoctorTbl = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel2.setBackground(new java.awt.Color(153, 153, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Hospital management Software");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(514, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(464, 464, 464)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user2.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 68, -1, -1));

        PatientLbl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        PatientLbl.setForeground(new java.awt.Color(102, 102, 255));
        PatientLbl.setText("Patient");
        PatientLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PatientLblMouseClicked(evt);
            }
        });
        getContentPane().add(PatientLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 78, -1, -1));

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(50, 2));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 100, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user2.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(746, 68, -1, -1));

        DoctorLbl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        DoctorLbl.setForeground(new java.awt.Color(102, 102, 255));
        DoctorLbl.setText("Doctor");
        DoctorLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DoctorLblMouseClicked(evt);
            }
        });
        getContentPane().add(DoctorLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(784, 78, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Doctor ID");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        DAIdTb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(DAIdTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 137, 112, 32));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("Name");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        DANameTb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(DANameTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 187, 112, 32));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("Phone");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 244, -1, -1));

        DAPhoneTb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(DAPhoneTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 241, 113, 31));

        DAAddressTb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(DAAddressTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 290, 113, 31));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 255));
        jLabel10.setText("Address");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 293, -1, -1));

        Type.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Type.setForeground(new java.awt.Color(0, 0, 255));
        Type.setText("Type");
        getContentPane().add(Type, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        DATypeCb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        DATypeCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cardiniogist", "Sentist", "Specialist", "Surgeon", "Psychiatrist" }));
        DATypeCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DATypeCbActionPerformed(evt);
            }
        });
        getContentPane().add(DATypeCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 347, 112, 31));

        DAPasswordTb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(DAPasswordTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 397, 112, 31));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 255));
        jLabel12.setText("Password");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 396, -1, -1));

        DASaveBtn.setBackground(new java.awt.Color(255, 255, 255));
        DASaveBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        DASaveBtn.setForeground(new java.awt.Color(51, 51, 255));
        DASaveBtn.setText("Save");
        DASaveBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DASaveBtnMouseClicked(evt);
            }
        });
        DASaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DASaveBtnActionPerformed(evt);
            }
        });
        getContentPane().add(DASaveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 104, -1));

        DAResetBtn.setBackground(new java.awt.Color(255, 255, 255));
        DAResetBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        DAResetBtn.setForeground(new java.awt.Color(51, 51, 255));
        DAResetBtn.setText("Reset");
        DAResetBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DAResetBtnMouseClicked(evt);
            }
        });
        getContentPane().add(DAResetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 104, -1));

        DADeleteBtn.setBackground(new java.awt.Color(255, 255, 255));
        DADeleteBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        DADeleteBtn.setForeground(new java.awt.Color(51, 51, 255));
        DADeleteBtn.setText("Delete");
        DADeleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DADeleteBtnMouseClicked(evt);
            }
        });
        getContentPane().add(DADeleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, 104, -1));

        DAEditBtn.setBackground(new java.awt.Color(255, 255, 255));
        DAEditBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        DAEditBtn.setForeground(new java.awt.Color(51, 51, 255));
        DAEditBtn.setText("Edit");
        DAEditBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DAEditBtnMouseClicked(evt);
            }
        });
        getContentPane().add(DAEditBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 104, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Windows-Turn-Off-icon.png"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 671, -1, -1));

        DAPrintBtn.setBackground(new java.awt.Color(255, 255, 255));
        DAPrintBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        DAPrintBtn.setForeground(new java.awt.Color(51, 51, 255));
        DAPrintBtn.setText("Print");
        DAPrintBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DAPrintBtnMouseClicked(evt);
            }
        });
        getContentPane().add(DAPrintBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 620, 104, 32));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 153, 255));
        jLabel15.setText("Doctor List");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 180, -1, -1));

        DoctorTbl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        DoctorTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DoctorID", "Name", "Phone", "Address", "Type", "Password"
            }
        ));
        DoctorTbl.setRowHeight(27);
        DoctorTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DoctorTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(DoctorTbl);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 993, 398));

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton1.setText("Hospital Information");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1166, 68, 164, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back5.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 710));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        int a = JOptionPane.showConfirmDialog(null, "Do you want to close the application","Select",JOptionPane.YES_NO_OPTION);
        
        if(a == 0){
            System.exit(0);
        }

    }//GEN-LAST:event_jLabel1MouseClicked

    private void DoctorLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DoctorLblMouseClicked
        new DoctorA().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DoctorLblMouseClicked

    private void DATypeCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DATypeCbActionPerformed
        //String title = (String) PGenderCb.getSelectedItem();
    }//GEN-LAST:event_DATypeCbActionPerformed

    private void DASaveBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DASaveBtnMouseClicked

    }//GEN-LAST:event_DASaveBtnMouseClicked

    private void DASaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DASaveBtnActionPerformed
        
        if(DAIdTb.getText().isEmpty()|| DANameTb.getText().isEmpty() || DAPhoneTb.getText().isEmpty() || DAAddressTb.getText().isEmpty() ||DATypeCb.getSelectedIndex() == -1 || DAPasswordTb.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Missing Information");
        }
        else{
           
           try{
               stmt = DBConnection.getStatementConnection();
               
               Integer DId = Integer.valueOf(DAIdTb.getText());
               String DName = DANameTb.getText();
               String DPhone = DAPhoneTb.getText();
               String DAddress = DAAddressTb.getText();
               String DType = DATypeCb.getSelectedItem().toString();
               String DPassword = DAPasswordTb.getText();
               
               DoctorController.doctor(DId, DName, DPhone, DAddress, DType, DPassword);
               
               JOptionPane.showMessageDialog(this, "Book saved");
               
               DisplayDoctors();
               Reset();
               
               
           } 
           catch(Exception e){
               e.printStackTrace();
           }
        }
        
    }//GEN-LAST:event_DASaveBtnActionPerformed

    private void DAResetBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DAResetBtnMouseClicked
        Reset();
    }//GEN-LAST:event_DAResetBtnMouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel16MouseClicked

    private void PatientLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PatientLblMouseClicked
        new Patient().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PatientLblMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        new HospitalInformation().setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void DoctorTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DoctorTblMouseClicked
        DefaultTableModel model = (DefaultTableModel)DoctorTbl.getModel();
        int MyIndex = DoctorTbl.getSelectedRow();
        DAIdTb.setText(model.getValueAt(MyIndex, 0).toString());
        DANameTb.setText(model.getValueAt(MyIndex, 1).toString());
        DAPhoneTb.setText(model.getValueAt(MyIndex, 2).toString());
        DAAddressTb.setText(model.getValueAt(MyIndex, 3).toString());
        DATypeCb.setSelectedItem(model.getValueAt(MyIndex, 4).toString());
        DAPasswordTb.setText(model.getValueAt(MyIndex, 5).toString());
        
    }//GEN-LAST:event_DoctorTblMouseClicked

    private void DAEditBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DAEditBtnMouseClicked
        if(DAIdTb.getText().isEmpty()|| DANameTb.getText().isEmpty() || DAPhoneTb.getText().isEmpty() || DAAddressTb.getText().isEmpty() ||DATypeCb.getSelectedIndex() == -1 || DAPasswordTb.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Missing Information");
        }
        else{
           try{
               stmt = DBConnection.getStatementConnection();
               String BId = DAIdTb.getText();
               String Query = "Update hospital_information.doctortbl set Name = '"+DANameTb.getText()+"',Phone = '"+DAPhoneTb.getText()+"',Address = '"+DAAddressTb.getText()+"', Type = '"+DATypeCb.getSelectedItem()+"',Password = '"+DAPasswordTb.getText()+"' where Doctor_ID = "+BId;
               stmt.executeUpdate(Query);
               
               JOptionPane.showMessageDialog(this, "Doctor Updated");
               DisplayDoctors();
               Reset();
           } 
           catch(Exception e){
               e.printStackTrace();
           }
        }
    }//GEN-LAST:event_DAEditBtnMouseClicked

    private void DADeleteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DADeleteBtnMouseClicked
        if(DAIdTb.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Missing Information");
        }
        else{
           try{
               stmt = DBConnection.getStatementConnection();
               String DId = DAIdTb.getText();
               String Query = "Delete from hospital_information.doctortbl where Doctor_ID="+DId;
               stmt.executeUpdate(Query);
               
               JOptionPane.showMessageDialog(this, "Doctor Deleted");
               DisplayDoctors();
               Reset();
           } 
           catch(Exception e){
               e.printStackTrace();
           }
        }
    }//GEN-LAST:event_DADeleteBtnMouseClicked

    private void DAPrintBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DAPrintBtnMouseClicked
        try 
        {
            DoctorTbl.print();
        } 
        catch (Exception e) 
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_DAPrintBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DAAddressTb;
    private javax.swing.JButton DADeleteBtn;
    private javax.swing.JButton DAEditBtn;
    private javax.swing.JTextField DAIdTb;
    private javax.swing.JTextField DANameTb;
    private javax.swing.JTextField DAPasswordTb;
    private javax.swing.JTextField DAPhoneTb;
    private javax.swing.JButton DAPrintBtn;
    private javax.swing.JButton DAResetBtn;
    private javax.swing.JButton DASaveBtn;
    private javax.swing.JComboBox<String> DATypeCb;
    private javax.swing.JLabel DoctorLbl;
    private javax.swing.JTable DoctorTbl;
    private javax.swing.JLabel PatientLbl;
    private javax.swing.JLabel Type;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
