/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.DBConnection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author DELL PC
 */
public class PatientHistoryA extends javax.swing.JFrame {

    /**
     * Creates new form PatientHistoryA
     */
    public PatientHistoryA() {
        initComponents();
        DisplayPatients();
    }
    
    Connection conn;
    Statement stmt;
    ResultSet Rs = null;
    
    private void DisplayPatients(){
        try {
            stmt = DBConnection.getStatementConnection();
            Rs = stmt.executeQuery("select * from hospital_information.parienttbl inner join parientdiagnosis where parienttbl.Patient_ID=parientdiagnosis.Patient_Id");
            PHistoryTbl.setModel(DbUtils.resultSetToTableModel(Rs));
            DBConnection.closeCon();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Connection Error");
        }
    
    }
    private void Reset(){
        PSymptomTb.setText("");
        PDiagnosisTb.setText("");
        PMedicinesTb.setText("");
        PWardReqCb.setSelectedIndex(0);
        PWardTypeCb.setSelectedIndex(0);
    }
    String TypeWard;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        DInfor = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PHistoryTbl = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        PSymptomTb = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        PDiagnosisTb = new javax.swing.JTextField();
        PMedicinesTb = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        DWardTypeLbl = new javax.swing.JLabel();
        PWardTypeCb = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        PDeleteBtn = new javax.swing.JButton();
        PEditBtn = new javax.swing.JButton();
        PRsetBtn = new javax.swing.JButton();
        PWardReqCb = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        PParientIdTb = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1351, 720));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel2.setBackground(new java.awt.Color(153, 153, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Hospital management Software");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(546, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(446, 446, 446)
                .addComponent(jLabel1)
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1389, 57);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 255));
        jLabel3.setText("Patient History");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(477, 78, 108, 22);

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setPreferredSize(new java.awt.Dimension(50, 2));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(477, 106, 108, 2);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/book2.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(439, 68, 32, 32);

        DInfor.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        DInfor.setForeground(new java.awt.Color(102, 102, 255));
        DInfor.setText("Diagnosis Information");
        DInfor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DInforMouseClicked(evt);
            }
        });
        getContentPane().add(DInfor);
        DInfor.setBounds(757, 78, 159, 22);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/stethoscope.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(719, 68, 32, 32);

        PHistoryTbl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        PHistoryTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient_ID", "Name", "Phone", "Address", "Gender", "Age", "Blood_Group", "Major_Disease", "Patient_Id", "Sympotom", "Medicines", "WardReq", "TypeWard"
            }
        ));
        PHistoryTbl.setRowHeight(27);
        PHistoryTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PHistoryTblMouseClicked(evt);
            }
        });
        PHistoryTbl.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                PHistoryTblComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(PHistoryTbl);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(75, 139, 1200, 325);

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton1.setText("Hospital Information");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1170, 70, 170, 25);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Windows-Turn-Off-icon.png"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel16MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel16);
        jLabel16.setBounds(10, 680, 32, 32);

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(51, 51, 255));
        jButton6.setText("Print");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(1109, 495, 104, 31);

        PSymptomTb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(PSymptomTb);
        PSymptomTb.setBounds(174, 547, 218, 32);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("Symptom's");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(75, 550, 81, 22);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("Diagnosis");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(75, 598, 69, 22);

        PDiagnosisTb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(PDiagnosisTb);
        PDiagnosisTb.setBounds(174, 595, 218, 32);

        PMedicinesTb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(PMedicinesTb);
        PMedicinesTb.setBounds(556, 496, 218, 32);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 255));
        jLabel10.setText("Medicines");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(424, 499, 73, 22);

        DWardTypeLbl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        DWardTypeLbl.setForeground(new java.awt.Color(0, 0, 255));
        DWardTypeLbl.setText("Type of Ward");
        getContentPane().add(DWardTypeLbl);
        DWardTypeLbl.setBounds(424, 599, 103, 22);

        PWardTypeCb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        PWardTypeCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General", "Single", "Duo" }));
        getContentPane().add(PWardTypeCb);
        PWardTypeCb.setBounds(556, 595, 167, 32);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 255));
        jLabel11.setText("Ward Required");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(424, 550, 110, 22);

        PDeleteBtn.setBackground(new java.awt.Color(255, 255, 255));
        PDeleteBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        PDeleteBtn.setForeground(new java.awt.Color(51, 51, 255));
        PDeleteBtn.setText("Delete");
        PDeleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PDeleteBtnMouseClicked(evt);
            }
        });
        getContentPane().add(PDeleteBtn);
        PDeleteBtn.setBounds(819, 495, 104, 31);

        PEditBtn.setBackground(new java.awt.Color(255, 255, 255));
        PEditBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        PEditBtn.setForeground(new java.awt.Color(51, 51, 255));
        PEditBtn.setText("Edit");
        PEditBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PEditBtnMouseClicked(evt);
            }
        });
        PEditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PEditBtnActionPerformed(evt);
            }
        });
        getContentPane().add(PEditBtn);
        PEditBtn.setBounds(819, 544, 104, 31);

        PRsetBtn.setBackground(new java.awt.Color(255, 255, 255));
        PRsetBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        PRsetBtn.setForeground(new java.awt.Color(51, 51, 255));
        PRsetBtn.setText("Reset");
        PRsetBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PRsetBtnMouseClicked(evt);
            }
        });
        getContentPane().add(PRsetBtn);
        PRsetBtn.setBounds(819, 595, 104, 31);

        PWardReqCb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        PWardReqCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YES", "NO" }));
        getContentPane().add(PWardReqCb);
        PWardReqCb.setBounds(556, 544, 167, 32);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 255));
        jLabel12.setText("Patient_Id");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(75, 499, 74, 22);

        PParientIdTb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(PParientIdTb);
        PParientIdTb.setBounds(174, 496, 218, 32);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Model/back5.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 1390, 730);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        int a = JOptionPane.showConfirmDialog(null, "Do you want to close the application","Select",JOptionPane.YES_NO_OPTION);

        if(a == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void DInforMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DInforMouseClicked
        new Diagnosis().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DInforMouseClicked

    private void PHistoryTblComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_PHistoryTblComponentShown
        //we coded here beceuse whenever our page load, it will get executed there.

    }//GEN-LAST:event_PHistoryTblComponentShown

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        new HospitalInformation().setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseEntered

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        try
        {
            PHistoryTbl.print();
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PDeleteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PDeleteBtnMouseClicked
        if(PParientIdTb.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Missing Information");
        }
        else{
           try{
               stmt = DBConnection.getStatementConnection();
               String BId = PParientIdTb.getText();
               String Query = "Delete from hospital_information.parientdiagnosis where Patient_ID="+BId;
               stmt.executeUpdate(Query);
               
               JOptionPane.showMessageDialog(this, "Patient Diagnosis Information Deleted");
               DisplayPatients();
               Reset();
           } 
           catch(Exception e){
               e.printStackTrace();
           }
        }
    }//GEN-LAST:event_PDeleteBtnMouseClicked

    private void PEditBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PEditBtnMouseClicked
        if(PParientIdTb.getText().isEmpty()|| PSymptomTb.getText().isEmpty() || PDiagnosisTb.getText().isEmpty() || PMedicinesTb.getText().isEmpty() ||PWardReqCb.getSelectedIndex() == -1)
        {
            JOptionPane.showMessageDialog(this, "Missing Information");
        }
        else{
           try{
               stmt = DBConnection.getStatementConnection();
               String BId = PParientIdTb.getText();
               TypeWard = PWardReqCb.getSelectedItem().toString();
               if(TypeWard == "NO"){
                   String typeward; 
                   typeward = "";
                   String Query = "Update hospital_information.parientdiagnosis set Symptom = '"+PSymptomTb.getText()+"',Diagnosis = '"+PDiagnosisTb.getText()+"',Medicines = '"+PMedicinesTb.getText()+"', WardReq = '"+PWardReqCb.getSelectedItem()+"',TypeWard= '"+typeward+"' where Patient_Id = "+BId;
                   stmt.executeUpdate(Query);
                   
               }
               else if(TypeWard == "YES"){
                   String typeward2; 
                   typeward2 = PWardTypeCb.getSelectedItem().toString();
                   String Query = "Update hospital_information.parientdiagnosis set Symptom = '"+PSymptomTb.getText()+"',Diagnosis = '"+PDiagnosisTb.getText()+"',Medicines = '"+PMedicinesTb.getText()+"', WardReq = '"+PWardReqCb.getSelectedItem()+"',TypeWard= '"+typeward2+"' where Patient_Id = "+BId;
                   stmt.executeUpdate(Query);
               }
               
               
               JOptionPane.showMessageDialog(this, "Patient Diagnosis Information Updated");
               DisplayPatients();
               Reset();
           } 
           catch(Exception e){
               e.printStackTrace();
           }
        }
    }//GEN-LAST:event_PEditBtnMouseClicked

    private void PRsetBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PRsetBtnMouseClicked
        Reset();
    }//GEN-LAST:event_PRsetBtnMouseClicked
    
    private void PHistoryTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PHistoryTblMouseClicked
        DefaultTableModel model = (DefaultTableModel)PHistoryTbl.getModel();
        int MyIndex = PHistoryTbl.getSelectedRow();
        PParientIdTb.setText(model.getValueAt(MyIndex, 8).toString());
        PSymptomTb.setText(model.getValueAt(MyIndex, 9).toString());
        PDiagnosisTb.setText(model.getValueAt(MyIndex, 10).toString());
        PMedicinesTb.setText(model.getValueAt(MyIndex, 11).toString());
        PWardReqCb.setSelectedItem(model.getValueAt(MyIndex, 12).toString());
        TypeWard = (String)PWardReqCb.getSelectedItem();
        PParientIdTb.setEditable(false);
        PWardTypeCb.setSelectedItem(model.getValueAt(MyIndex, 13).toString());
        
        
        
    }//GEN-LAST:event_PHistoryTblMouseClicked

    private void PEditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PEditBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PEditBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientHistoryA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientHistoryA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientHistoryA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientHistoryA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientHistoryA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DInfor;
    private javax.swing.JLabel DWardTypeLbl;
    private javax.swing.JButton PDeleteBtn;
    private javax.swing.JTextField PDiagnosisTb;
    private javax.swing.JButton PEditBtn;
    private javax.swing.JTable PHistoryTbl;
    private javax.swing.JTextField PMedicinesTb;
    private javax.swing.JTextField PParientIdTb;
    private javax.swing.JButton PRsetBtn;
    private javax.swing.JTextField PSymptomTb;
    private javax.swing.JComboBox<String> PWardReqCb;
    private javax.swing.JComboBox<String> PWardTypeCb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
